# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
default: &default
  telegram_bot_api_token: <%= ENV['TELEGRAM_BOT_API_TOKEN'] %>
  telegram_bot_name: <%= ENV['TELEGRAM_BOT_NAME'] %>

development:
  <<: *default
  secret_key_base: 7e71052b7ef223734a87a15e4ddbf58f6c1aa81158a021c54ba56524a1eb8e74b671fd711b78c7a86d97454a6dda72583cab745c9a2ff3be85876bedaa2c2aa0

test:
  <<: *default
  secret_key_base: 4c665fc3e0ed155415a749de27fd6c465756b27297542bec7e8c09829d24789435fb84d93843be06f96130499c51e3a9115a53aea800f57cdb3598c851343722

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
